baseURL = "https://www.liuguisheng.vip/"
languageCode = "en-us"
title = "凤凰城下的小码农"
description = "一个被代码耽误的大艺术家"
publishDir = "docs"


[params]
    icon = "header.jpg"
    formspree = "https://formspree.io/f/mleabgzd"
    toc = true

    [params.header]
        name = "凤凰城下的小码农"
        subtitle = "一个被代码耽误的大艺术家 !"
        image = "header.jpg"
        otherText = "网站升级中...........  更多内容请关注公众号【凤凰城下的小码农】"

    [params.about.button]
        text = "这里"


    [params.contact]
        title = "联系我"

        [params.contact.form]
            [params.contact.form.name]
                text = "姓名："
                placeholder = "请输入姓名："
            [params.contact.form.email]
                text = "电子邮件："
                placeholder = "请输入电子邮件："
            [params.contact.form.phone]
                text = "电话："
                placeholder = "请输入电话："
            [params.contact.form.message]
                text = "内容："
                placeholder = "请输入内容："
            [params.contact.form.button]
                text = "提交"

    [params.portfolio]
        title = "精选文章"


        [[params.portfolio.projectList]]
            title = "如何用小米手环6替换太空人表盘"
            img = "cabin.png"
            url = "/post/如何用小米手环6替换太空人表盘"
        [[params.portfolio.projectList]]
            title = "如何用小米手环6替换太空人表盘"
            img = "cabin.png"
            url = "/post/如何用小米手环6替换太空人表盘"
        [[params.portfolio.projectList]]
            title = "如何用小米手环6替换太空人表盘"
            img = "cabin.png"
            url = "/post/如何用小米手环6替换太空人表盘"

    [params.project]
        title = "开源项目"

        [[params.project.list]]
            title = "react-admin-plus"
            img = "cabin.png"
            url = "https://github.com/qisi007/react-admin-plus"
        [[params.project.list]]
            title = "react-admin-plus"
            img = "cabin.png"
            url = "https://github.com/qisi007/react-admin-plus"
        [[params.project.list]]
            title = "react-admin-plus"
            img = "cabin.png"
            url = "https://github.com/qisi007/react-admin-plus"

    
    [params.footer.location]
        title = "123123"
        address = "www.liuguisheng.vip"
    
     [params.footer.social]
        title = "友情链接"

        [[params.footer.social.networks]]
            link = "https://github.com/qisi007"
            icon = "fa-github"
        [[params.footer.social.networks]]
            link = "https://github.com/qisi007"
            icon = "fa-github"
        [[params.footer.social.networks]]
            link = "https://github.com/qisi007"
            icon = "fa-github"
        [[params.footer.social.networks]]
            link = "https://github.com/qisi007"
            icon = "fa-github"
        [[params.footer.social.networks]]
            link = "https://github.com/qisi007"
            icon = "fa-github"

    
    [params.footer]
        copyright = "power by 凤凰山下的小码农"

    

  

