baseURL = "https://www.liuguisheng.vip/"
languageCode = "en-us"
title = "凤凰城下的小码农"
description = "一个被代码耽误的大艺术家"
theme = "freelancer"
publishDir = "docs"


[params]
    [params.header]
        name = "凤凰城下的小码农"
        subtitle = "一个被代码耽误的大艺术家 !"
        image = "header.jpg"
        otherText = "网站升级中...........  更多内容请关注公众号【凤凰城下的小码农】"




